name: Deploy WordPress Plugin

env:
  PHP_VERSION: '8.1'
  NODE_VERSION: '16'
  PLUGIN_NAME: 'wp-job-openings'

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Cache NPM packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install NPM Dependencies
        run: npm ci

      - name: Install Composer Dependencies
        if: hashFiles('composer.json')
        run: composer install --no-dev --optimize-autoloader

      - name: Build Assets
        run: npm run build

      - name: Create deployment package
        run: |
          mkdir build
          rsync -av --progress . build/ \
          --exclude=/.git/ \
          --exclude=/.github/ \
          --exclude=/node_modules/ \
          --exclude=/build/ \
          --exclude=/src/ \
          --exclude=.gitignore \
          --exclude=.eslintrc \
          --exclude=gulpfile.js \
          --exclude=package.json \
          --exclude=package-lock.json \
          --exclude=composer.json \
          --exclude=composer.lock \
          --exclude=README.md \
          --exclude=.eslintignore \
          --exclude=.browserslistrc

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "build/"
          TARGET: "${{ secrets.REMOTE_PATH }}/wp-content/plugins/${{ env.PLUGIN_NAME }}/"
          ARGS: "-rltgoDzvO --delete"
          SCRIPT_AFTER: |
            chmod -R 755 "${{ secrets.REMOTE_PATH }}/wp-content/plugins/${{ env.PLUGIN_NAME }}"
