name: Deploy WordPress Plugin

env:
  PHP_VERSION: '8.1'
  NODE_VERSION: '16'
  PLUGIN_NAME: 'wp-job-openings'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install NPM Dependencies
        run: npm ci

      - name: Install Composer Dependencies
        if: hashFiles('composer.json')
        run: composer install --no-dev --optimize-autoloader

      - name: Build Assets
        run: npm run build

      # Add SSH key setup step
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          if_key_exists: replace

      # Add known_hosts
      - name: Adding Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -avz --delete \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='node_modules' \
          --exclude='vendor' \
          --exclude='.gitignore' \
          --exclude='.eslintrc' \
          --exclude='gulpfile.js' \
          --exclude='package.json' \
          --exclude='package-lock.json' \
          --exclude='composer.json' \
          --exclude='composer.lock' \
          --exclude='README.md' \
          --exclude='.eslintignore' \
          --exclude='.browserslistrc' \
          ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}/wp-content/plugins/${{ env.PLUGIN_NAME }}/

      - name: Set permissions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            chmod -R 755 ${{ secrets.REMOTE_PATH }}/wp-content/plugins/${{ env.PLUGIN_NAME }}
