name: Test SSH File Creation

on: 
  workflow_dispatch:  # Manual trigger

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH File Creation
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            ls -la /home/awsmstaging/public_html/jobs/wp-content/
            echo "Testing file creation..."
            echo "This file was created by GitHub Actions on $(date)" > ${{ secrets.REMOTE_PATH }}/test.txt
            if [ -f "${{ secrets.REMOTE_PATH }}/test.txt" ]; then
              echo "✅ File created successfully"
              cat "${{ secrets.REMOTE_PATH }}/test.txt"
            else
              echo "❌ File creation failed"
            fi
            ls -la ${{ secrets.REMOTE_PATH }}
