name: Test Deployment
env:
  PLUGIN_NAME: 'wp-job-openings'
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_USER: ${{ secrets.REMOTE_USER }}
  REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
  DEPLOY_KEY_PATH: ~/.ssh/deploy_key

on:
  workflow_dispatch:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ${{ env.DEPLOY_KEY_PATH }}
          chmod 600 ${{ env.DEPLOY_KEY_PATH }}
          chmod 700 ~/.ssh
          eval $(ssh-agent -s)
          ssh-add ${{ env.DEPLOY_KEY_PATH }}
          ssh-keyscan -H ${{ env.REMOTE_HOST }} >> ~/.ssh/known_hosts
          # Debug SSH connection
          ssh -v -i ${{ env.DEPLOY_KEY_PATH }} -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} 'pwd'
        shell: bash

      - name: Test Rsync
        run: |
          rsync -avzh --stats --progress -e "ssh -i ${{ env.DEPLOY_KEY_PATH }}" --delete \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='node_modules' \
          --exclude='vendor' \
          --exclude='.gitignore' \
          --exclude='.eslintrc' \
          --exclude='gulpfile.js' \
          --exclude='package.json' \
          --exclude='package-lock.json' \
          --exclude='composer.json' \
          --exclude='composer.lock' \
          --exclude='README.md' \
          --exclude='.eslintignore' \
          --exclude='.browserslistrc' \
          ./ ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}:${{ env.REMOTE_PATH }}/wp-content/plugins/${{ env.PLUGIN_NAME }}/
